config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'application#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/saque' => 'contas#saque_index', as: :saque_index
  get '/deposito' => 'contas#deposito_index', as: :deposito_index
  get '/transferencia' => 'contas#transferencia_index', as: :transferencia_index
  get '/minha_conta' => 'contas#minha_conta_index', as: :minha_conta_index
  match '/extrato' => 'contas#extrato_index', as: :extrato_index, via: [:get, :post]
  post '/realizar_saque' => 'contas#realizar_saque', as: :realizar_saque
  post '/realizar_deposito' => 'contas#realizar_deposito', as: :realizar_deposito
  post '/realizar_transferencia' => 'contas#realizar_transferencia', as: :realizar_transferencia
  post '/encerrar_conta' => 'contas#encerrar_conta', as: :encerrar_conta
  post '/reabrir_conta' => 'contas#reabrir_conta', as: :reabrir_conta


end

app/models/conta.rb
class Conta < ActiveRecord::Base

  belongs_to :user

  scope :ativo, -> { where(ativo: true) }
  #Verificar i18n
  validates :saldo, :numericality => { :greater_than_or_equal_to => 0 }

  def saldo_to_s
    "R$ #{self.saldo/100},00"
  end

  def movimentacoes
    Movimentacao.where("conta_origem_id = ? OR conta_destino_id = ?", self.id, self.id)
  end

  def self.deposito(conta, valor)
    Conta.transaction do
      conta.saldo += valor
      conta.save!
      movimentacao = Movimentacao.new(conta_destino_id: conta.id, valor: valor, tipo_movimentacao_id: TipoMovimentacao.get_id_by_nome("Depósito"))
      movimentacao.save!
      return nil
    end
    rescue ActiveRecord::RecordInvalid => exception
      return exception.message
  end

  def saque(valor)
    Conta.transaction do
      self.saldo -= valor
      self.save!
      movimentacao = Movimentacao.new(conta_origem_id: self.id, conta_destino_id: self.id, valor: valor, tipo_movimentacao_id: TipoMovimentacao.get_id_by_nome("Saque"))
      movimentacao.save!
      return nil
    end
    rescue ActiveRecord::RecordInvalid => exception
      return exception.message
  end

  def self.horario_comercial
    hora = DateTime.now.hour
    if Array(2..6).include? DateTime.now.wday && (hora >= 9 && hora <= 18)
      return true
    else
      return false
    end
  end

  def self.transferencia(conta_origem, conta_destino, valor)
    
    taxa = 0
    taxa += 10 if valor > 1000
    if horario_comercial
      taxa+=5
    else
      taxa+=7
    end
    Conta.transaction do
      conta_origem.saldo -= (valor+taxa)
      conta_destino.saldo += valor
      conta_origem.save!
      conta_destino.save!
      movimentacao = Movimentacao.new(conta_origem_id: conta_origem.id, conta_destino_id: conta_destino.id, valor: valor, tipo_movimentacao_id: TipoMovimentacao.get_id_by_nome("Transferência"))
      movimentacao.save!
      return nil     
    end
    rescue ActiveRecord::RecordInvalid => exception
      return exception.message
  end

  def extrato(data_inicio = DateTime.now.strftime("01/%m/%Y").to_datetime, data_fim = DateTime.now)
    self.movimentacoes.where(created_at: data_inicio..data_fim)
  end


end

app/models/movimentacao.rb
class Movimentacao < ActiveRecord::Base

  belongs_to :tipo_movimentacao
  belongs_to :conta_origem, class_name: 'Conta'
  belongs_to :conta_destino, class_name: 'Conta'

  validates :tipo_movimentacao_id, presence: true
  validates :valor, :numericality => { :greater_than => 0 }
  validates :valor, :conta_destino_id, :tipo_movimentacao_id, presence: true

  before_save :centavos_conversao

  def valor_to_s
    "R$ #{self.valor/100}"
  end

end

app/models/tipo_movimentacao.rb
class TipoMovimentacao < ActiveRecord::Base

  has_many :movimentacao

  def self.get_id_by_nome(nome)
    TipoMovimentacao.find_by_nome(nome).id
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :conta

  has_many :movimentacoes, through: :conta

  validates :email, uniqueness: true
  validates :nome, presence: true

  before_create :create_conta

  def create_conta
    self.build_conta({saldo: 0})
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :html, :xml, :json, :js

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def index

  end

  protected

    def configure_permitted_parameters
        # Fields for sign up
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:nome, :email, :password, :password_confirmation) }
        # Fields for editing an existing account
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:nome, :email, :password, :password_confirmation, :current_password)}
    end

end

app/controllers/contas_controller.rb
class ContasController < ApplicationController

  before_action :authenticate_user!, except: [:deposito_index, :realizar_deposito]
  before_action :check_conta_ativo, only: [:saque, :transferencia, :realizar_saque, :realizar_transferencia]

  def check_conta_ativo
    redirect_to minha_conta_index_path if !current_user.conta.ativo
  end

  def saque_index 
    @saque = Movimentacao.new 
  end

  def deposito_index
    @deposito = Movimentacao.new 
  end

  def transferencia_index
    @transferencia = Movimentacao.new
  end

  def extrato_index
    if params[:extrato]
      d1, m1, y1 = params[:extrato][:data_inicio].split("/").map(&:to_i)
      d2, m2, y2 = params[:extrato][:data_fim].split("/").map(&:to_i)

      if (d1 && m1 && y1) && !Date.valid_date?(y1,m1,d1) || (d2 && m2 && y2) && !Date.valid_date?(y2,m2,d2) 
        redirect_to extrato_index_path, flash: {error: "Formato de data inválido. Favor utilizar dd/mm/aaaa" }
      elsif (!d1 || !m1 || !y1 || !d2 || !m2 || !y2)
        redirect_to extrato_index_path, flash: {error: "Formato de data inválido. Favor utilizar dd/mm/aaaa" }
      else  
        @data_inicio = params[:extrato][:data_inicio].try(:to_datetime)
        @data_fim = params[:extrato][:data_fim].try(:to_datetime)
      end
    end
    if (!@data_inicio || !@data_fim)
      @data_inicio = DateTime.now.strftime("01/%m/%Y").to_datetime
      @data_fim = DateTime.now
    end
    @movimentacoes = current_user.conta.extrato(@data_inicio, @data_fim).sort_by(&:created_at)
  end

  def minha_conta_index
    @usuario = current_user
  end

  def realizar_saque
    erros = current_user.conta.saque(params["movimentacao"]["valor"].delete(',').delete('.').to_i)
    if erros.nil?
      redirect_to saque_index_path, notice: 'Saque realizado com sucesso.'
    else
      redirect_to saque_index_path, flash: { error: erros }
    end
  end

  def realizar_deposito
    erros = Conta.deposito(Conta.find(params["movimentacao"]["conta_destino_id"].delete(',').delete('.').to_i), params["movimentacao"]["valor"].to_i)
    if erros.nil?
      redirect_to deposito_index_path, notice: 'Depósito realizado com sucesso.'
    else
      redirect_to deposito_index_path, flash: { error: erros }
    end
  end

  def realizar_transferencia
    erros = Conta.transferencia(current_user.conta, Conta.find(params["movimentacao"]["conta_destino_id"].delete(',').delete('.').to_i), params["movimentacao"]["valor"].to_i)
    if erros.nil?
      redirect_to transferencia_index_path, notice: 'Transferência realizada com sucesso.'
    else
      redirect_to transferencia_index_path, flash: { error: erros }
    end
  end

  def encerrar_conta
    conta = Conta.find(params[:id])
    conta.ativo = false
    conta.desativado_data = Date.today
    conta.save
    redirect_to minha_conta_index_path
  end

  def reabrir_conta
    conta = Conta.find(params[:id])
    conta.ativo = true
    conta.save
    redirect_to minha_conta_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contas/deposito_index.html.slim
h3 Depósito
= simple_form_for @deposito, url: realizar_deposito_path do |f|
  = f.input :valor, input_html: { class: 'currency' }, as: :string
  = f.association :conta_destino, collection: Conta.ativo, label_method: lambda {|conta| conta.user.nome}, include_blank: false, input_html: {class: 'chosen-select'}
  = f.submit "Realizar Depósito", class: 'btn-primary'
end

app/views/contas/extrato_index.html.slim
h3 Extrato
br
h4 Período:
= simple_form_for :extrato, url: extrato_index_path do |f|
  = f.datetime_field :data_inicio, class: "dateinput", :as => :string
  '
  '/
  = f.datetime_field :data_fim, class: "dateinput", :as => :string
  = f.submit "Filtrar", class: 'btn-primary'
br
h5 = "Exibindo saldo para o período #{@data_inicio.strftime("%d/%m/%Y")} - #{@data_fim.strftime("%d/%m/%Y")}"
table class="table table-striped" id="extrato"
  thead
    tr
      th Horário
      th Tipo de Movimentação
      th Titular da Conta
      th Valor
  tbody class="extrato-index"
  - @movimentacoes.each do |movimentacao|
    tr
      td = movimentacao.created_at.strftime("%d/%m/%Y às %H:%M")
      td = movimentacao.tipo_movimentacao.nome
      td = movimentacao.conta_destino.try(:user).try(:nome)
      td = movimentacao.valor_to_s

app/views/contas/minha_conta_index.html.slim
- if @usuario.conta.ativo == false
  div class="alert alert-warning" role="alert"
    = "Sua conta foi desativada em #{@usuario.conta.desativado_data.strftime("%d/%m/%Y")}"
.container.target
  .row-eq-height
    .col-sm-3
      = image_tag("http://pcdoctorti.com.br/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png", class: "profilepic")
    .col-sm-4.col-md-10
      .profileinfo
        blockquote
          h2 = @usuario.nome
  br/
  .row
    .col-sm-3
      /! left col
      ul.list-group
        li.list-group-item.text-muted contenteditable="false"  Informações
        li.list-group-item.text-right
          span.pull-left
            strong Saldo:
          = @usuario.conta.saldo_to_s
        li.list-group-item.text-right
          span.pull-left
            strong Membro desde:
          = @usuario.created_at.strftime("%d/%m/%Y")
        li.list-group-item.text-right
          span.pull-left
            strong Último login:
          = @usuario.last_sign_in_at.strftime("%d/%m/%Y")
      ul.list-group
        li.list-group-item.text-muted contenteditable="false"  Gerenciar Conta
        li.list-group-item
          - if @usuario.conta.ativo         
            ul
              li = link_to "Encerrar Conta", encerrar_conta_path(id: @usuario.conta), method: :post
          - else
            ul
              li = link_to "Reabrir Conta", reabrir_conta_path(id: @usuario.conta), method: :post

    /! /col-3
    .col-sm-9 contenteditable="false" style=""
      .panel.panel-default
        .panel-heading Extrato/Mês
        .panel-body
          table class="table table-striped" id="extrato"
            thead
              tr
                th Horário
                th Tipo de Movimentação
                th Titular da Conta
                th Valor
            tbody class="extrato-index"
            - @usuario.conta.extrato.each do |movimentacao|
              tr
                td = movimentacao.created_at.strftime("%d/%m/%Y às %H:%M")
                td = movimentacao.tipo_movimentacao.nome
                td = movimentacao.conta_destino.try(:user).try(:nome)
                td = movimentacao.valor_to_s

app/views/contas/saque_index.html.slim
h3 Saque
= simple_form_for @saque, url: realizar_saque_path do |f|
  = f.input :valor, input_html: { class: 'currency' }, as: :string
  = f.submit "Realizar Saque", class: 'btn-primary'
end

app/views/contas/transferencia_index.html.slim
h3 Transferência
= simple_form_for @transferencia, url: realizar_transferencia_path do |f|
  = f.association :conta_destino, collection: Conta.ativo, label_method: lambda {|conta| conta.user.nome}, include_blank: false, input_html: {class: 'chosen-select'}
  = f.input :valor, input_html: { class: 'currency' }, as: :string
  = f.button :submit, class: 'btn-primary' do
    Realizar Transferência
  end
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
  	meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Integra - Bankline"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all", 'data-turbolinks-track' => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = favicon_link_tag 'favicon.png', :rel => 'shortcut icon'


  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a href="/"
          = image_tag("logo.png", alt: "Logotipo Integra", class: "nav-logo")
          span class="navbar-brand" Integra Bankline
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" href="#" 
                = "<span class=\"glyphicon glyphicon-th-list\"></span> Transações".html_safe
                b.caret
              ul class="dropdown-menu" role="menu" aria-labelledby="dLabel"
                - if current_user && current_user.conta && current_user.conta.ativo
                  li= link_to "<span class=\"glyphicon glyphicon glyphicon-circle-arrow-right\"></span> Saque".html_safe, saque_index_path
                li= link_to "<span class=\"glyphicon glyphicon glyphicon-circle-arrow-right\"></span> Depósito".html_safe, deposito_index_path
                - if current_user && current_user.conta && current_user.conta.ativo
                  li= link_to "<span class=\"glyphicon glyphicon glyphicon-circle-arrow-right\"></span> Transferência".html_safe, transferencia_index_path
                  li= link_to "<span class=\"glyphicon glyphicon glyphicon-circle-arrow-right\"></span> Extrato por período".html_safe, extrato_index_path
            - if current_user
              li= link_to "<span class=\"glyphicon glyphicon-user\"></span> Minha Conta".html_safe, minha_conta_index_path              
              li= link_to "<span class=\"glyphicon glyphicon-off\"></span> Sair".html_safe, destroy_user_session_path,:method => :delete
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield